import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Adam",
      email: "adam@gmail.com",
      password: bcrypt.hashSync("stop123", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/Shiseido.jpeg',
        description: 'Shiseido is one of the oldest cosmetic companies in the world',
        rating: 4.5,
        numReviews: 1620,
      },
    },
    {
      name: "Catherine",
      email: "kate@gmail.com",
      password: bcrypt.hashSync("123", 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Benefiance Wrinkle Smoothing Cream",
      category: "Brands",
      image: "/images/ShiseidoBenefianceWrinkleSmoothingCreamEnriched.png",
      sku: "730852149540",
      price: 70,
      countInStock: 10,
      brand: "Shiseido",
      rating: 3.5,
      numReviews: 10,
      description:
        "Benefiance Wrinkle Smoothing Cream Enriched delivers deep hydration and fresh ingredients to dry skin to promote a radiant and youthful look. Targeting fine lines, the moisturizer is infused with ReNeura Technology+™ and KOMBU-Bounce Complex to ensure resilience and prevent future wrinkles.",
    },
    {
      name: "Sulwhasoo Skin Reinforcing Set for Men",
      category: "Skin Care",
      image: "/images/SulwhasooSkinReinforcingSetMen.jpg",
      sku: "8809685815051",
      price: 120,
      countInStock: 12,
      brand: "Sulwhasoo",
      rating: 4.0,
      numReviews: 16,
      description:
        "Our Men's face care collection features multi-use products that help address a variety of ... Skin Reinforcing Emulsion for Men.",
    },
    {
      name: "Gongjinhyang:Mi Essential Primer Whoo",
      category: "Makeup",
      image: "/images/MiEssentialPrimerWhoo.jpg",
      sku: "8801051416701",
      price: 48,
      countInStock: 11,
      brand: "WHOO",
      rating: 4.0,
      numReviews: 21,
      description:
        "This primer supports natural cellular vitality, protects against free radicals and works to help tone the skin and refine facial features, creating a luminous, flawless canvas for comfortable, long-lasting color.",
    },
    {
      name: "STEAM WARMING BACK PATCH LAVENDER",
      category: "Makeup",
      image: "/images/KaoBackPatchLavenderScent.jpg",
      sku: "4901301348128",
      price: 12.99,
      countInStock: 8,
      brand: "KAO",
      rating: 4.5,
      numReviews: 50,
      description:
        "Combined with a relaxing scent of lavender, the self-warming Kao Steam Warming Back Mask  comfortably envelopes your back with warm steam of about 40°C to soothe aching bones, relieve stress, and ease tension. Use this at the end of the day or take a break with this mask to feel more relaxed! This product may be used before going to bed, while traveling, or while simply relaxing at home. It’s great to use after a long day of staring at the computer or at any other digital devices.",
    },
    {
      name: "One Push kit #4C cnnamon brown 80g",
      category: "Hair Care",
      image: "/images/OnePushKit4CcnnamonBrown.jpg",
      sku: "033859001041",
      price: 10,
      countInStock: 50,
      brand: "Bigen",
      rating: 4.0,
      numReviews: 30,
      description:
        "Innovative ONE PUSH bottle empowers you to color your hair on a whim.",
    },
    {
      name: "AXXZIA Venus Recipe Plus AG Drink 30 Bags",
      category: "Health",
      image: "/images/AGDrink.jpg",
      sku: "4560413151097",
      price: 212.5,
      countInStock: 6,
      brand: "AXXZIA",
      rating: 4.5,
      numReviews: 29,
      description: "Healthy drink by Axxzia for nutrition and health.",
    },
    {
      name: "AMINO Mason Whip Cream Body Soap Rich",
      category: "Body Care",
      image: "/images/AMINOMason.jpg",
      sku: "4589919561803",
      price: 16.99,
      countInStock: 6,
      brand: "AMINO",
      rating: 4.5,
      numReviews: 60,
      description: "Amino acid-based surfactant formula to create hydrated, supple skin.",
    },
    {
      name: "AMINO Mason Whip Cream Body Soap Rich",
      category: "Face Mask",
      image: "/images/100xLGMask.png",
      sku: "8801051029093",
      price: 225,
      countInStock: 16,
      brand: "AMINO",
      rating: 3.5,
      numReviews: 60,
      description: "10% off LG Masks + Free Hand Sanitizer or Lysol Spray.",
    },
    {
      name: "WHOO Spa Essence Shampoo",
      category: "Hair Care",
      image: "/images/WhooShampoo.jpeg",
      sku: "8801051362930",
      price: 28.00,
      countInStock: 5,
      brand: "WHOO",
      rating: 4.0,
      numReviews: 20,
      description:
        "Hair-loss prevention and scalp care.Soothing Head Skin.Nourishing, Recover Scalp Balancing.",
    },
    {
      name: "IPSA Creative Concealer EX SPF25",
      category: "Makeup",
      image: "/images/IPSAExSpf25.jpeg",
      sku: "4931449433080",
      price: 55.00,
      countInStock: 18,
      brand: "IPSA",
      rating: 4.0,
      numReviews: 18,
      description:
        "Ipsa Creative Concealer EX SPF25 PA+++ offers 3 different shades to use separately or combined to flawlessly conceal blemishes such as dark circles, acne scars, redness, and discoloration.",
    },
    {
      name: "LG Natural Fresh Herb Toothpaste",
      category: "Oral Care",
      image: "/images/LGHerbalToothpaste.jpeg",
      sku: "4931449433080",
      price: 55.00,
      countInStock: 18,
      brand: "LG",
      rating: 4.0,
      numReviews: 26,
      description:
        "The Bamboo salt toothpaste is made by mixing salt and bamboo, baking at 1832°F/1000°C for 9 times.",
    },
    {
      name: "Kobayashi Fever Cooling Gel Pad for Adults",
      category: "Medical",
      image: "/images/KobayashiFeverPad.jpeg",
      sku: "4987072011195",
      price: 7.99,
      countInStock: 6,
      brand: "Kobayashi",
      rating: 4.0,
      numReviews: 56,
      description:
        "Comfortable and stable cooling effect persists for about 8 hours per sheet.",
    },
    {
      name: "DHC Deep Cleansing Oil Makeup Remover 200ml",
      category: "Makeup",
      image: "/images/DHCCleansingOil.jpeg",
      sku: "3887072011191",
      price: 26.99,
      countInStock: 14,
      brand: "DHC",
      rating: 4.0,
      numReviews: 36,
      description:
        "The original Japanese 1-step oil cleanser melts away makeup and dissolves impurities, leaving your skin clean, soft and radiant.",
    },
  ],
};

export default data;
